# -*- coding: utf-8 -*-
"""Project2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yiXfV173RfE0THYjHjeieWOacBI7jjYu?usp=sharing
"""

# =========================
# Import Libraries
# =========================

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, f1_score, accuracy_score

# =========================
# Load Dataset
# =========================

iris = load_iris()

X = iris.data
y = iris.target

# (Optional) View dataset
df = pd.DataFrame(X, columns=iris.feature_names)
df['target'] = y

print(df.head())

# =========================
# Shuffle + Split Data
# =========================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    shuffle=True
)

# =========================
# Feature Scaling
# =========================

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# =========================
# Elbow Method (Visualization)
# =========================

error_rates = []
k_values = range(1, 21)

for k in k_values:

    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train, y_train)

    y_pred = knn.predict(X_test)

    error = np.mean(y_pred != y_test)
    error_rates.append(error)

# Best K
best_k = error_rates.index(min(error_rates)) + 1

# =========================
# Plot Elbow Curve
# =========================

plt.figure(figsize=(10,6))

plt.plot(k_values, error_rates, marker='o', linestyle='--')

plt.scatter(best_k, min(error_rates), s=200)

plt.text(best_k, min(error_rates),
         f' Best K = {best_k}',
         fontsize=12)

plt.title('Elbow Method For Optimal K')

plt.xlabel('K Value')

plt.ylabel('Error Rate')

plt.xticks(k_values)

plt.grid(True)

plt.show()

print("Best K Value =", best_k)

# =========================
# Train Final Model
# =========================

model = KNeighborsClassifier(n_neighbors=best_k)

model.fit(X_train, y_train)

# =========================
# Prediction
# =========================

y_pred = model.predict(X_test)

# =========================
# Evaluation
# =========================

cm = confusion_matrix(y_test, y_pred)

f1 = f1_score(y_test, y_pred, average='weighted')

accuracy = accuracy_score(y_test, y_pred)

print("\nConfusion Matrix:\n", cm)

print("\nF1 Score:", f1)

print("\nAccuracy:", accuracy)

# =========================
# Confusion Matrix Heatmap
# =========================

plt.figure(figsize=(6,5))

sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=iris.target_names,
    yticklabels=iris.target_names
)

plt.title('Confusion Matrix Heatmap')

plt.xlabel('Predicted Label')

plt.ylabel('True Label')

plt.show()
